name: Build and upload artifact

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-pc-windows-gnu
          override: true
          components: rust-src
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target x86_64-pc-windows-gnu --release -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort
      - name: Rename to .dva
        shell: cmd
        run: |
          rename target\x86_64-pc-windows-gnu\release\launcher_egui.dll launcher_egui.dva
      - uses: actions/upload-artifact@v2
        with:
          path: target/x86_64-pc-windows-gnu/release/launcher_egui.dva
